### ISSUE TITLE
Publish as VS Code extension

### ISSUE THREAD

**Issue by i-ky** [red-tux/zabbix_template_schema#1]
[YAML extension for VS Code](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) allows other extensions to contribute YAML schemas [via `yamlValidation` contribution point](https://github.com/redhat-developer/vscode-yaml#mapping-a-schema-in-an-extension). This way VS Code user can simply install an extension contributing Zabbix template schema instead of manually pulling schema from GitHub and adding it to `yaml.schemas` in `settings.json`. It will also make it easier to discover this schema (by searching VS Code Marketplace).

**Comment by red-tux** [comment]
The long term goal is to have it added to the json schema store, that way it can become even more automatic for end users.  However for right now I need to keep things file based for the contribution point for testing.

**Comment by red-tux** [comment]
However that does not preclude changing the instructions to point to the raw github entry point for others to test etc.  Feel free to reopen and or submit a PR to update the instructions.
